version: '3.7'

services:

  app-backend:
    container_name: app-backend
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - backend

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  backend: